const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('codexManager', {
  loadState: () => ipcRenderer.invoke('load-state'),
  loadBackupStatus: () => ipcRenderer.invoke('load-backup-status'),
  getNasSetupState: () => ipcRenderer.invoke('get-nas-setup-state'),
  detectCompanyNas: () => ipcRenderer.invoke('detect-company-nas'),
  listNasDepartments: () => ipcRenderer.invoke('list-nas-departments'),
  listNasEmployees: (department) => ipcRenderer.invoke('list-nas-employees', department),
  activateNasBackup: (department, employee) => ipcRenderer.invoke('activate-nas-backup', department, employee),
  retryNasBackup: () => ipcRenderer.invoke('retry-nas-backup'),
  retryLaunchAtLogin: () => ipcRenderer.invoke('retry-launch-at-login'),
  openLoginItemSettings: () => ipcRenderer.invoke('open-login-item-settings'),
  listNasBackupDevices: () => ipcRenderer.invoke('list-nas-backup-devices'),
  loadIncrementalBackupSessions: (deviceId) => ipcRenderer.invoke('load-incremental-backup-sessions', deviceId),
  setAutoRestore: (enabled) => ipcRenderer.invoke('set-auto-restore', enabled),
  createSnapshot: (name) => ipcRenderer.invoke('create-snapshot', name),
  loadSnapshotSessions: (snapshotId) => ipcRenderer.invoke('load-snapshot-sessions', snapshotId),
  openSnapshot: (snapshotId) => ipcRenderer.invoke('open-snapshot', snapshotId),
  chooseRestoreProtectionMode: (options) => ipcRenderer.invoke('choose-restore-protection-mode', options),
  restoreSnapshotConversations: (snapshotId, protectionMode) => ipcRenderer.invoke('restore-snapshot-conversations', snapshotId, protectionMode),
  restoreSnapshotFull: (snapshotId, protectionMode) => ipcRenderer.invoke('restore-snapshot-full', snapshotId, protectionMode),
  restoreSnapshotSession: (snapshotId, sessionId, protectionMode) => ipcRenderer.invoke('restore-snapshot-session', snapshotId, sessionId, protectionMode),
  restoreSnapshotSessions: (snapshotId, sessionIds, protectionMode) => ipcRenderer.invoke('restore-snapshot-sessions', snapshotId, sessionIds, protectionMode),
  restoreIncrementalBackupSessions: (deviceId, sessionIds, protectionMode) => ipcRenderer.invoke('restore-incremental-backup-sessions', deviceId, sessionIds, protectionMode),
  deleteSnapshot: (snapshotId) => ipcRenderer.invoke('delete-snapshot', snapshotId),
  deleteSnapshots: (snapshotIds) => ipcRenderer.invoke('delete-snapshots', snapshotIds),
  restoreSession: (sessionId, protectionMode) => ipcRenderer.invoke('restore-session', sessionId, protectionMode),
  deleteSession: (sessionId) => ipcRenderer.invoke('delete-session', sessionId),
  deleteSessions: (sessionIds) => ipcRenderer.invoke('delete-sessions', sessionIds),
  loadConversation: (sessionId) => ipcRenderer.invoke('load-conversation', sessionId),
  openSessionFile: (sessionId) => ipcRenderer.invoke('open-session-file', sessionId),
  revealSessionFile: (sessionId) => ipcRenderer.invoke('reveal-session-file', sessionId),
  openCodexRoot: () => ipcRenderer.invoke('open-codex-root'),
  openVaultRoot: () => ipcRenderer.invoke('open-vault-root')
});
